/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;


import FriendManagementBackend.*;
import UserManagementBackend.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author daree
 */
public class ManageFriends extends javax.swing.JFrame {

    Newsfeed newsfeed;
    User currentuser;
    Management manage;
    UserDataBase userDB =UserDataBase.getDatabase();

    public ManageFriends(Newsfeed newsfeed , User currentuser, Management manage) {
        initComponents();
       this.newsfeed=newsfeed;
       this.currentuser=currentuser;
       this.manage = manage;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReq = new javax.swing.JButton();
        back = new javax.swing.JButton();
        sendreq = new javax.swing.JButton();
        suggestButton = new javax.swing.JButton();
        viewFriends = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        viewReq.setBackground(new java.awt.Color(255, 204, 255));
        viewReq.setText("View Requests");
        viewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 204, 255));
        back.setText("Return To NewsFeed");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        sendreq.setBackground(new java.awt.Color(255, 204, 255));
        sendreq.setText("Send Request");
        sendreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendreqActionPerformed(evt);
            }
        });

        suggestButton.setBackground(new java.awt.Color(255, 204, 255));
        suggestButton.setText(" Suggestions");
        suggestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestButtonActionPerformed(evt);
            }
        });

        viewFriends.setBackground(new java.awt.Color(255, 204, 255));
        viewFriends.setText("View Friends");
        viewFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendreq, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back)
                    .addComponent(suggestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestButton)
                    .addComponent(viewReq))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendreq)
                    .addComponent(viewFriends))
                .addGap(50, 50, 50)
                .addComponent(back)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        newsfeed.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void viewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqActionPerformed
        // TODO add your handling code here:
    
       ViewRequests viewReqFrame=new ViewRequests(this,currentuser,manage);
        
        viewReqFrame.setVisible(true);
        setVisible(false);
        
      
        
    }//GEN-LAST:event_viewReqActionPerformed

    private void sendreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendreqActionPerformed
        // TODO add your handling code here:
        
      String senderid= currentuser.getUserId();
      ArrayList<Requests> requests =manage.getUserRequests(senderid);
      String usernametoadd= JOptionPane.showInputDialog("Enter username:");
      User receiver=userDB.getUserByUsername(usernametoadd);
      
      String receiverid=receiver.getUserId();
      Requests R= new Requests(senderid,receiverid);
      manage.addrequest(R);
    }//GEN-LAST:event_sendreqActionPerformed

    private void suggestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestButtonActionPerformed
        // TODO add your handling code here:
        SuggestedFriends suggestFrame=new SuggestedFriends(this,currentuser,manage);
        suggestFrame.setVisible(true);
        setVisible(false);
        
        
        
    }//GEN-LAST:event_suggestButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        newsfeed.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void viewFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFriendsActionPerformed
        // TODO add your handling code here:
        ViewFriends  viewfriendsframe=new ViewFriends(this,currentuser,manage);
        viewfriendsframe.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_viewFriendsActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton sendreq;
    private javax.swing.JButton suggestButton;
    private javax.swing.JButton viewFriends;
    private javax.swing.JButton viewReq;
    // End of variables declaration//GEN-END:variables
}
