/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import FriendManagementBackend.Requests;
import FriendManagementBackend.RequestsDatabase;
import FriendManagementBackend.RequestsManagement;
import UserManagementBackend.User;
import UserManagementBackend.UserDataBase;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author daree
 */
public class ManageFriends extends javax.swing.JFrame {

    
    NewsFeed newsfeed;
    User currentuser;
    RequestsManagement reqm=new RequestsManagement();
    UserDataBase userDB =UserDataBase.getDatabase();
   // RequestsDatabase reqDB=RequestsDatabase.getinstance();
    /**
     * Creates new form ManageFriends
     */
    public ManageFriends(NewsFeed newsfeed , User currentuser) {
        initComponents();
       this.newsfeed=newsfeed;
       this.currentuser=currentuser;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReq = new javax.swing.JButton();
        back = new javax.swing.JButton();
        sendreq = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        viewReq.setText("View Requests");
        viewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqActionPerformed(evt);
            }
        });

        back.setText("Return To NewsFeed");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        sendreq.setText("Send Request");
        sendreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendreqActionPerformed(evt);
            }
        });

        jButton2.setText(" suggestions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendreq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(back))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(viewReq)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendreq)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        newsfeed.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void viewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqActionPerformed
        // TODO add your handling code here:
      
       String Userid= currentuser.getUserId();
       ArrayList<Requests> requests =reqm.getUserRequests(Userid);
        RequestsManage reqmanage=new RequestsManage(this,requests);
        
        reqmanage.setVisible(true);
        setVisible(false);
        
        
        
    }//GEN-LAST:event_viewReqActionPerformed

    private void sendreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendreqActionPerformed
        // TODO add your handling code here:
        
      String senderid= currentuser.getUserId();
      ArrayList<Requests> requests =reqm.getUserRequests(senderid);
      String usernametoadd= JOptionPane.showInputDialog("Enter username:");
      User receiver=userDB.getUserByUsername(usernametoadd);
      String receiverid=receiver.getUserId();
      Requests R= new Requests(senderid,receiverid);
      requests.add(R);
      
      //  RequestsManage reqmanage=new RequestsManage(this,requests);
    }//GEN-LAST:event_sendreqActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        newsfeed.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton sendreq;
    private javax.swing.JButton viewReq;
    // End of variables declaration//GEN-END:variables
}
