/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import ProfileManagmentFrontend.ViewProfile;
import UserManagementBackend.User;
import UserManagementBackend.UserDataBase;
import UserManagementBackend.UserLog;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Newsfeed extends javax.swing.JFrame {
     ViewProfile profile;
     UserDataBase database =UserDataBase.getDatabase();
     User user =UserDataBase.getCurrentUser();
     UserLog log=new UserLog(UserDataBase.getDatabase());
     Home home=Home.getInstance();
    public Newsfeed() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visitProfile = new javax.swing.JButton();
        ManageFriends = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("News Feed");

        visitProfile.setBackground(new java.awt.Color(255, 204, 255));
        visitProfile.setText("Visit Profile");
        visitProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitProfileActionPerformed(evt);
            }
        });

        ManageFriends.setBackground(new java.awt.Color(255, 204, 255));
        ManageFriends.setText("Manage Friends");

        logout.setBackground(new java.awt.Color(255, 204, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout)
                    .addComponent(ManageFriends)
                    .addComponent(visitProfile))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(visitProfile)
                .addGap(32, 32, 32)
                .addComponent(ManageFriends)
                .addGap(32, 32, 32)
                .addComponent(logout)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitProfileActionPerformed
        // TODO add your handling code here:
        ViewProfile profile=new ViewProfile();
        profile.setVisible(true);
        
        
        
    }//GEN-LAST:event_visitProfileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        log.logOut(user);
        JOptionPane.showMessageDialog(this, "Logging out and return to home");
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageFriends;
    private javax.swing.JButton logout;
    private javax.swing.JButton visitProfile;
    // End of variables declaration//GEN-END:variables
}
