/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import ContentCreationFrontend.AddPostFront;
import ContentCreationFrontend.AddStoryFront;
import ProfileManagmentFrontend.ViewProfile;
import UserManagementBackend.User;
import UserManagementBackend.UserDataBase;
import UserManagementBackend.UserLog;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Newsfeed extends javax.swing.JFrame {
     ViewProfile profile;
     UserDataBase database =UserDataBase.getDatabase();
     User user =UserDataBase.getCurrentUser();
     UserLog log=new UserLog(UserDataBase.getDatabase());
     Home home=Home.getInstance();
    public Newsfeed() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVisitProfile = new javax.swing.JButton();
        ManageFriends = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        newsfeedLabel = new javax.swing.JLabel();
        Addpost = new javax.swing.JButton();
        addstory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Newsfeed");

        btnVisitProfile.setBackground(new java.awt.Color(255, 204, 255));
        btnVisitProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVisitProfile.setText("Visit Profile");
        btnVisitProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitProfileActionPerformed(evt);
            }
        });

        ManageFriends.setBackground(new java.awt.Color(255, 204, 255));
        ManageFriends.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManageFriends.setText("Manage Friends");

        logout.setBackground(new java.awt.Color(255, 204, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        newsfeedLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newsfeedLabel.setText("Newsfeed");

        Addpost.setBackground(new java.awt.Color(255, 204, 255));
        Addpost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Addpost.setText("Add Post");
        Addpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddpostActionPerformed(evt);
            }
        });

        addstory.setBackground(new java.awt.Color(255, 204, 255));
        addstory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addstory.setText("Add Story");
        addstory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsfeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ManageFriends)
                        .addGap(44, 44, 44)
                        .addComponent(Addpost)
                        .addGap(34, 34, 34)
                        .addComponent(addstory)
                        .addGap(52, 52, 52)
                        .addComponent(btnVisitProfile)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(newsfeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageFriends)
                    .addComponent(btnVisitProfile)
                    .addComponent(logout)
                    .addComponent(Addpost)
                    .addComponent(addstory))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisitProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitProfileActionPerformed
        // TODO add your handling code here:
        ViewProfile profile = new ViewProfile(this);
        profile.setVisible(true);
    }//GEN-LAST:event_btnVisitProfileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        log.logOut(user);
        JOptionPane.showMessageDialog(this, "Logging out and return to home");
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

    private void addstoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstoryActionPerformed
        // TODO add your handling code here:
        AddStoryFront story=new AddStoryFront();
        story.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addstoryActionPerformed

    private void AddpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddpostActionPerformed
        // TODO add your handling code here:
         AddPostFront post=new AddPostFront();
        post.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_AddpostActionPerformed

  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addpost;
    private javax.swing.JButton ManageFriends;
    private javax.swing.JButton addstory;
    private javax.swing.JButton btnVisitProfile;
    private javax.swing.JButton logout;
    private javax.swing.JLabel newsfeedLabel;
    // End of variables declaration//GEN-END:variables
}
