/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import FriendManagementBackend.Requests;
import UserManagementBackend.User;
import UserManagementBackend.UserDataBase;
import java.awt.ScrollPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author daree
 */
public class RequestsManage extends javax.swing.JFrame {
    

    
    ManageFriends manageF;
    User currentuser;
    ArrayList<Requests> requests;
    UserDataBase userDB =UserDataBase.getDatabase();
    /**
     * Creates new form RequestsManagement
     */
    public RequestsManage(ManageFriends manageF, ArrayList<Requests> requests) {
        initComponents();
        this.manageF=manageF;
        this.requests=requests;
        filljlist(requests);
      //  this.currentuser=currentuser;
    }
    
    public void filljlist(ArrayList<Requests> requests)
    {
        
        DefaultListModel<String> model=new DefaultListModel();

     for(Requests r:requests)
        {   String userid1=r.getSenderID();
        User u=userDB.getUserById(userid1);
       String username=u.getUsername();
            model.addElement(username);
        }
     
      JList<String> list=new JList<>(model);
      
       jScrollPane1.setViewportView(list);
      String selectedusername=list.getSelectedValue();

        
        //listreq.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listreq = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        listreq.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listreq);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        manageF.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listreq;
    // End of variables declaration//GEN-END:variables
}
