/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import FriendManagementBackend.*;
import UserManagementBackend.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author daree
 */
public class SuggestedFriends extends javax.swing.JFrame {

    ManageFriends manageframe;
    User currentuser;
    Management manage;
    UserDataBase userDB =UserDataBase.getDatabase();
    RequestsDatabase  requestsDB=RequestsDatabase.getinstance();
   
    /**
     * Creates new form SuggestedFriends
     */
    public SuggestedFriends( ManageFriends manageframe,User currentuser,Management manage) {
        initComponents();
        this.manageframe=manageframe;
        this.currentuser=currentuser;
        this.manage=manage;
        fillList();
        
    }

    public void fillList()
    {
      
        requestsDB.loadFile();
        
         ArrayList<String> suggestedIDs= manage.getSuggestedFriends(currentuser.getUserId());
         
       DefaultListModel<String> model=new DefaultListModel();
      
       for(String ID : suggestedIDs)
       {
           User u = userDB.getUserById(ID);
           String username =u.getUsername();
           model.addElement(username);
       }
        
        list.setModel(model);
       jScrollPane1.setViewportView(list);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        sendrequest = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suggested Friends");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("           People You May Know");

        jScrollPane1.setViewportView(list);

        sendrequest.setBackground(new java.awt.Color(255, 204, 255));
        sendrequest.setText("Send Request");
        sendrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrequestActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendrequest)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        manageframe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sendrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrequestActionPerformed
        // TODO add your handling code here:
       
               int index= list.getSelectedIndex();
     if(index>-1)
     {
         String selectedusername=list.getSelectedValue();
         User u = userDB.getUserByUsername(selectedusername);
        String receiverid=u.getUserId();
     String SenderId=currentuser.getUserId();
     
         Requests R = new Requests (SenderId,receiverid);
         manage.addrequest(R);
    
      fillList();  
     }
     
     else
     {
          JOptionPane.showMessageDialog(this, "You Should Select a request", "  Message ", JOptionPane.PLAIN_MESSAGE);
     }
       
        
         
    }//GEN-LAST:event_sendrequestActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         setVisible(false);
        manageframe.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton sendrequest;
    // End of variables declaration//GEN-END:variables
}
