/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import FriendManagementBackend.*;
import UserManagementBackend.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author daree
 */
public class ViewFriends extends javax.swing.JFrame {

    /**
     * Creates new form ViewFriends
     */
    
       ManageFriends manageframe;
    User currentuser;
    Management manage;
    UserDataBase userDB =UserDataBase.getDatabase();
    public ViewFriends(ManageFriends manageframe,User currentuser,Management manage) {
        initComponents();
        
         this.manageframe=manageframe;
        this.currentuser=currentuser;
        this.manage=manage;
        fillList();
    }

     public void fillList()
    {
        ArrayList<String> friendsIDS=manage.getUserFriendsIDs(currentuser.getUserId());
             
        DefaultListModel<String> model=new DefaultListModel();

     for(String id :friendsIDS)
        {   
          
            User u=userDB.getUserById(id);
           String username=u.getUsername();
            model.addElement(username);
        }
     
       list.setModel(model);
       jScrollPane1.setViewportView(list);
      
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        remove = new javax.swing.JButton();
        block = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Your Friends");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        remove.setBackground(new java.awt.Color(255, 204, 255));
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        block.setBackground(new java.awt.Color(255, 204, 255));
        block.setText("Block");
        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("             Your Friends");

        back.setBackground(new java.awt.Color(255, 204, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove)
                    .addComponent(block)
                    .addComponent(back))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remove)
                        .addGap(18, 18, 18)
                        .addComponent(block)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
        // TODO add your handling code here:
        
     int index= list.getSelectedIndex();
     if(index>-1)
     {
         String selectedusername=list.getSelectedValue();
         User u =userDB.getUserByUsername(selectedusername);
        String id2=u.getUserId();
        String id1=currentuser.getUserId();
        Friends f= manage.getFriend(id1, id2);
        manage.removefriend(f);
        manage.BlockUser(id1, id2);
     
      fillList();  
     }
     
     else
     {
          JOptionPane.showMessageDialog(this, "You Should Select a Friend to remove", "  Message ", JOptionPane.PLAIN_MESSAGE);
     }
     
    }//GEN-LAST:event_blockActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        manageframe.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        
           int index= list.getSelectedIndex();
     if(index>-1)
     {
         String selectedusername=list.getSelectedValue();
         User u =userDB.getUserByUsername(selectedusername);
        String id2=u.getUserId();
        String id1=currentuser.getUserId();
        Friends f= manage.getFriend(id1, id2);
        manage.removefriend(f);
     
      fillList();  
     }
     
     else
     {
          JOptionPane.showMessageDialog(this, "You Should Select a Friend to remove", "  Message ", JOptionPane.PLAIN_MESSAGE);
     }
     
        
     
        
        
    }//GEN-LAST:event_removeActionPerformed

 
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         manageframe.setVisible(true);
      
    }//GEN-LAST:event_formWindowClosed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton block;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
