/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProfileManagmentFrontend;

import ProfileManagementBackend.ProfileManager;
import UserManagementBackend.UserDataBase;
import java.awt.Image;
import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class userProfile extends javax.swing.JFrame {

    ProfileManager manager;

    /**
     * Creates new form Profile
     */
    public userProfile() {
        initComponents();
        manager = new ProfileManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePhotoLabel = new javax.swing.JLabel();
        coverPhotoLabel = new javax.swing.JLabel();
        btnUploadProfilePhoto = new javax.swing.JButton();
        btnUploadCoverPhoto = new javax.swing.JButton();
        bioLabel = new javax.swing.JLabel();
        btnSaveProfile = new javax.swing.JButton();
        bioScrollPane = new javax.swing.JScrollPane();
        bioTextArea = new javax.swing.JTextArea();
        postsScrollPane = new javax.swing.JScrollPane();
        postsJPanel = new javax.swing.JPanel();
        friendsScrollPane = new javax.swing.JScrollPane();
        friendsJList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnViewFriends = new javax.swing.JButton();
        btnViewPosts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profilePhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagmentFrontend/defaultProfilePhoto.jpeg"))); // NOI18N

        coverPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfileManagmentFrontend/defaultCoverPhoto.jpg"))); // NOI18N

        btnUploadProfilePhoto.setBackground(new java.awt.Color(255, 204, 255));
        btnUploadProfilePhoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUploadProfilePhoto.setText("Upload Profile Photo");
        btnUploadProfilePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadProfilePhotoActionPerformed(evt);
            }
        });

        btnUploadCoverPhoto.setBackground(new java.awt.Color(255, 204, 255));
        btnUploadCoverPhoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUploadCoverPhoto.setText("Upload Cover Photo");
        btnUploadCoverPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCoverPhotoActionPerformed(evt);
            }
        });

        bioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bioLabel.setText("Bio");

        btnSaveProfile.setBackground(new java.awt.Color(255, 204, 255));
        btnSaveProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveProfile.setText("Save");
        btnSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProfileActionPerformed(evt);
            }
        });

        bioTextArea.setColumns(20);
        bioTextArea.setRows(5);
        bioScrollPane.setViewportView(bioTextArea);

        postsJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        postsJPanel.setLayout(new javax.swing.BoxLayout(postsJPanel, javax.swing.BoxLayout.LINE_AXIS));
        postsScrollPane.setViewportView(postsJPanel);

        friendsScrollPane.setViewportView(friendsJList);

        jButton1.setText("Change Password");

        btnViewFriends.setText("View Friends");

        btnViewPosts.setText("View Posts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnUploadProfilePhoto))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(bioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(profilePhotoLabel)))
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(coverPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewFriends)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewPosts)
                                .addGap(83, 83, 83)
                                .addComponent(btnUploadCoverPhoto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(friendsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(postsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addComponent(btnSaveProfile)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coverPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaveProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUploadCoverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnViewPosts)
                                            .addComponent(btnViewFriends))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(friendsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(postsScrollPane))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profilePhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUploadProfilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadProfilePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadProfilePhotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filePath = file.getAbsolutePath();
            ImageIcon icon = new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            profilePhotoLabel.setIcon(icon);
            manager.updatePhoto(filePath, "profile");
        }

    }//GEN-LAST:event_btnUploadProfilePhotoActionPerformed

    private void btnSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProfileActionPerformed
        String bio = bioTextArea.getText();
       // String password = new String(profilePasswordField.getPassword());
        int flag = 0;
        String oldPassword = UserDataBase.getCurrentUser().getPassword();
        String oldBio = UserDataBase.getCurrentUser().getBio();
        if (!bio.isEmpty()) {
            if (!bio.equals(oldBio)) {
                manager.updateBio(bio);
                flag = 1;
            } else {
                JOptionPane.showMessageDialog(this, "New bio  matches old bio", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
   /*     if (!password.isEmpty()) {
            try {
                if (!password.equals(oldPassword)) {
                    manager.updatePassword(password);
                    flag = 1;
                } else {
                    JOptionPane.showMessageDialog(this, "New password matches old password", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(userProfile.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

*/
        if (flag == 1) {
            JOptionPane.showMessageDialog(this, "Profile updated successfully!");
        }

    }//GEN-LAST:event_btnSaveProfileActionPerformed

    private void btnUploadCoverPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCoverPhotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filePath = file.getAbsolutePath();
            ImageIcon icon = new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            coverPhotoLabel.setIcon(icon);
            manager.updatePhoto(filePath, "cover");
        }
    }//GEN-LAST:event_btnUploadCoverPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioLabel;
    private javax.swing.JScrollPane bioScrollPane;
    private javax.swing.JTextArea bioTextArea;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JButton btnUploadCoverPhoto;
    private javax.swing.JButton btnUploadProfilePhoto;
    private javax.swing.JButton btnViewFriends;
    private javax.swing.JButton btnViewPosts;
    private javax.swing.JLabel coverPhotoLabel;
    private javax.swing.JList<String> friendsJList;
    private javax.swing.JScrollPane friendsScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel postsJPanel;
    private javax.swing.JScrollPane postsScrollPane;
    private javax.swing.JLabel profilePhotoLabel;
    // End of variables declaration//GEN-END:variables
}
